"""Synthetic AcmePay engineering history. `rel` lists linked record ids."""
RECORDS = [
 {"id":"INC-101","type":"incident","service":"payment-service","date":"2026-01-14","title":"Payment timeout issue",
  "text":"Payment requests to the card processor timed out and failed without retrying. Root cause: no retry on transient upstream timeouts. Resolved by adding retry with backoff.","rel":["PR-247"]},
 {"id":"PR-247","type":"pull_request","service":"payment-service","date":"2026-01-20","title":"Add retry mechanism to payment client",
  "text":"Introduced retry logic with exponential backoff in the payment client after INC-101 timeouts. Commit a82f91.","rel":["INC-101","a82f91","DEC-01","INC-103"]},
 {"id":"a82f91","type":"commit","service":"payment-service","date":"2026-01-19","title":"feat(payment): retry on timeout","text":"Retry loop with backoff added to payment client.","rel":["PR-247"]},
 {"id":"DEC-01","type":"decision","service":"payment-service","date":"2026-01-18","title":"Retry with backoff over circuit breaker",
  "text":"Decision: use client-side retry with exponential backoff because timeouts were transient. Trade-off: retries can duplicate requests without idempotency.","rel":["PR-247"]},
 {"id":"INC-103","type":"incident","service":"payment-service","date":"2026-03-02","title":"Duplicate payment requests",
  "text":"Duplicate payment requests under timeout conditions. Root cause: retry behavior from PR #247 resent charges without idempotency keys. Fixed by PR #251 adding idempotency protection.","rel":["PR-247","PR-251"]},
 {"id":"PR-251","type":"pull_request","service":"payment-service","date":"2026-03-04","title":"Add idempotency keys to payments",
  "text":"Added idempotency protection because retries could create duplicate payment requests. Fix for INC-103.","rel":["INC-103","DP-v2.4.1"]},
 {"id":"DP-v2.4.1","type":"deployment","service":"payment-service","date":"2026-03-10","title":"Deployment v2.4.1",
  "text":"v2.4.1 shipped idempotency fix. Later saw connection pool exhausted in payment-service (INC-105); pool limits raised and monitoring added.","rel":["PR-251","INC-105"]},
 {"id":"INC-105","type":"incident","service":"payment-service","date":"2026-03-11","title":"Connection pool exhausted",
  "text":"Connection pool exhausted in payment-service after deployment v2.4.1. Resolution: connection limits increased and monitoring added. Error rate returned to normal.","rel":["DP-v2.4.1"]},
 {"id":"INC-102","type":"incident","service":"auth-service","date":"2026-02-05","title":"Authentication token failures",
  "text":"Auth tokens rejected after clock skew between nodes. Resolved by adding token expiry leeway.","rel":[]},
 {"id":"INC-104","type":"incident","service":"notification-service","date":"2026-04-08","title":"Notification queue backlog",
  "text":"Notification queue backlog after consumer crash loop. Resolved by scaling consumers and adding dead-letter queue.","rel":[]},
 {"id":"PR-318","type":"pull_request","service":"payment-service","date":"2026-05-12","title":"Refactor database connection handling",
  "text":"Refactored database connection management in payment-service.","rel":["DP-v3.1.0"]},
 {"id":"DP-v3.1.0","type":"deployment","service":"payment-service","date":"2026-05-14","title":"Deployment v3.1.0 (rolled back)",
  "text":"v3.1.0 caused latency and error rate increase; deployment was rolled back. Root cause: database connection handling from PR #318 (INC-142).","rel":["PR-318","INC-142"]},
 {"id":"INC-142","type":"incident","service":"payment-service","date":"2026-05-14","title":"Latency and errors after v3.1.0",
  "text":"Latency and error rate rose after v3.1.0; rollback performed. Root cause: database connection handling.","rel":["DP-v3.1.0","PR-318"]},
]
